### ISSUE TITLE
无法读取k8s的secret

### ISSUE THREAD

**Issue by kaybinwong** [AlloVince/drone-ci-demo#5]
无法读取k8s的secret

```

1 | + echo ${DOCKER_PASSWORD}
-- | --
2 |  
3 | + echo ${username}
4 |  
5 | + echo ${password}
6

```

**Comment by AlloVince** [comment]
请补充更多信息，如 drone repo的secret设置，drone k8s 配置等

**Comment by kaybinwong** [comment]
drone yaml
```
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: drone-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-secrets
  namespace: cd
  labels:
    app: drone-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-secrets
  template:
    metadata:
      labels:
        app: drone-secrets
    spec:
      containers:
        - name: drone-secrets
          image: drone/kubernetes-secrets
          imagePullPolicy: Always
          env:
            - name: SECRET_KEY
              value: 558f3eacbfd5922157cbfe34823ab921
          ports:
            - name: http
              containerPort: 3000
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: drone-secrets-service
  namespace: cd
spec:
  selector:
    app: drone-secrets
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
  namespace: cd
  labels:
    app: drone-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-server
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
        - name: drone-server
          image: drone/drone:1.0.0-rc.6
          imagePullPolicy: Always
          env:
            - name: DRONE_KUBERNETES_ENABLED
              value: "true"
            - name: DRONE_KUBERNETES_NAMESPACE
              value: cd
            - name: DRONE_GITLAB_CLIENT_ID
              value: dabde6f82c009320483267cf565e32a1ec82318310ced47fa6574eee0bccfa5f
            - name: DRONE_GITLAB_SERVER
              value: http://gitlab.xx.com
            - name: DRONE_GITLAB_CLIENT_SECRET
              value: b9cf0f5c4206a1c19fbfec40c84056e3a5e6432a71450866fc7f345bc2642664
            - name: DRONE_SERVER_HOST
              value: drone.xx.com
            - name: DRONE_SERVER_PROTO
              value: http
            - name: DRONE_DATABASE_DRIVER
              value: sqlite3
            - name: DRONE_DATABASE_DATASOURCE
              value: "/drone/drone.sqlite"
            - name: DRONE_USER_CREATE
              value: username:huangkaibin,admin:true
            - name: DRONE_SECRET_SECRET
              value: 558f3eacbfd5922157cbfe34823ab921
            - name: DRONE_SECRET_ENDPOINT
              value: http://drone-secrets-service
            - name: DRONE_RPC_SECRET
              value: 5bRDQ5YI8krbKoYGy7K330Ow
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
            - name: drone-pvc
              mountPath: "/drone"
      volumes:
        - name: drone-pvc
          persistentVolumeClaim:
            claimName: drone-pvc
      restartPolicy: Always

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-pvc
  namespace: cd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard


---
kind: Service
apiVersion: v1
metadata:
  name: drone-server-service
  namespace: cd
spec:
  selector:
    app: drone-server
  ports:
    - protocol: TCP
      port: 80
      name: http


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: drone-ingress
  namespace: cd
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
spec:
  rules:
    - host: drone.xx.com
      http:
        paths:
          - path: /
            backend:
              serviceName: drone-server-service
              servicePort: 80
---
---
apiVersion: v1
kind: Secret
type: Opaque
data:
  DOCKER_PASSWORD: MTIzMTIzYWJjCg==
  password: MTIzMTIzYWJjCg==
  username: MjQwNzMyNjQzQHFxLmNvbQo=
metadata:
  name: drone-secrets
  namespace: cd
```

.drone.yaml
```
---
kind: pipeline
name: deploy

steps:
  - name: print-env
    image: docker
    environment:
      username:
        from_secret: username
      password:
        from_secret: password
    commands:
    - echo $${DOCKER_PASSWORD}
    - echo $${username}
    - echo $${password}


---
kind: secret
name: username
get:
  path: drone-secrets
  name: username

---
kind: secret
name: password
get:
  path: drone-secrets
  name: password
```

drone的配置基本跟一致，只是我们使用的是gitlab
